controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    bumperbot_controller:
      type: diff_drive_controller/DiffDriveController
  
simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint


bumperbot_controller:  
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.17
    wheel_radius: 0.033
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -0.5
    linear.x.max_acceleration: 0.8
    linear.x.min_acceleration: 0.8

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.7
    angular.z.min_velocity: -1.7
    angular.z.max_acceleration: 1.5
    angular.z.min_acceleration: -1.5